language: go
go:
  - 1.8.3
services: docker

install: true

script:
  - ./openebs-build.sh

deploy:
  - provider: script
    script: ./openebs-deploy.sh
    on:
      tags: true

branches:
  only:
  - release
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
